name: Python Linting

# CINTENT >> MANUAL_TRIGGER
# on:
#   pull_request:
#     branches:
#       - master
#     paths:
#       - 'setup.py'
#       - 'lithops/**'
#   workflow_dispatch: 
#   # this allows to run the workflow manually through the github dashboard
on: [repository_dispatch, workflow_dispatch]

jobs:

  flake8:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Lithops repository
        uses: actions/checkout@v4

      - name: Install Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # CINTENT >> INSERT_CINTENT
      - uses: JavidDitty/setup-cintent@3638849e94bdb037f0a405375686a8550e6df904
        with:
          nonblocking: true

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -U flake8

      - name: Install Lithops
        run: |
          pip3 install -U .
      
      - name: Lint with flake8
        run: |
          flake8 lithops --count --max-line-length=180 --statistics --ignore W605,W503

      # CINTENT >> INSERT_CINTENT
      - name: Upload CIntent Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ env.CINTENT_ARTIFACT_NAME }}
          path: ${{ env.CINTENT_LOGS }}
